--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/surveybuilderteams/AdvancedModerator
build-by-default: true
branches:
- master
projects:
  AdvancedModeration:
    path: AdvancedModeration/
...
