name: AdvancedModeration
main: AdminBuilder1\AdvancedModeration\advancedmoderation
description: A better way to moderatate your server
api: [3.22.0, 3.22.1]
version: 1.0
  
commands:
    advancedmod:
        description: "A very high tech moderatation system"
        usage: "/advancedmod [args]..."
        aliases: [advmod]
        
permissions:
   advancedmod.command:
    description: "starts the AdvancedModeration commands"
    default: op
   advancedmod.help:
    description: "list all the commands of AdvancedModeration"
    default: op
   advancedmod.announce:
    description: "Shares a public message to everyone"
    default: op