name: AdvancedModeration
main: AdminBuilder1\AdvancedModeration\advancedmoderation
description: A better way to moderatate your server
website: https://github.com/surveybuilderteams/AdvancedModerator
api: [3.22.0, 4.0.0]
version: 2.0.0
  
commands:
    advancedmod:
        description: "A very high tech moderatation system"
        usage: "/advancedmod help"
        aliases: [advmod]
        
permissions:
   advancedmod.allow:
    description: "Allows Plugin OP to enable/disable the actions from the plugin"
    default: notop
   advancedmod.command:
    description: "starts the AdvancedModeration commands"
    default: op
   advancedmod.help:
    description: "list all the commands of AdvancedModeration"
    default: op
   advancedmod.announce:
    description: "Shares a public message to everyone"
    default: op
   advancedmod.pmsg:
    description: "Sends private message to a player"
    default: op
   advancedmod.getIP:
    description: "Grabs IP address from user"
    default: op
   advancedmod.gm:
    description: "Sets own gamemode"
    default: op
   advancedmod.gmall:
    description: "Sets everyone gamemode"
    default: op
   advancedmod.tp:
    description: "teleports to a player or coords"
    default: op
   advancedmod.kick:
    description: "kicks a player"
    default: op
   advancedmod.kickall:
    description: "kicks all player"
    default: op
   advancedmod.vanish:
    description: "hides from users"
    default: op
   advancedmod.fly:
    description: "allows you to fly"
    default: op
   advancedmod.mute:
    description: "allows you to mute player"
    default: op
   advancedmod.tmute:
    description: "allows you to temp. mute player"
    default: op
   advancedmod.unmute:
    description: "allows you to unmute player"
    default: op
   advancedmod.mutelist:
    description: "allows you to see listed muted players"
    default: op
   advancedmod.muteall:
    description: "allows you to mute all players"
    default: op
   advancedmod.tmuteall:
    description: "allows you to temp. mute all players"
    default: op
   advancedmod.unmuteall:
    description: "allows you to unmute all players"
    default: op
   advancedmod.op:
    description: "allows you to op users"
    default: op
   advancedmod.deop:
    description: "allows you to deop users"
    default: op
   advancedmod.opall:
    description: "allows you to op all users"
    default: op
   advancedmod.deopall:
    description: "allows you to deop all users"
    default: op
   advancedmod.banlist:
    description: "allows you to display the list of banned players"
    default: op
   advancedmod.ban:
    description: "allows you to ban player"
    default: op
   advancedmod.unban:
    description: "allows you to unban player"
    default: op
   advancedmod.banip:
    description: "allows you to ban player ip"
    default: op 
   advancedmod.unbanip:
    description: "allows you to unban player ip"
    default: op
   advancedmod.warn:
    description: "allows you to warn a player"
    default: op
   advancedmod.tban:
    description: "allows you to temp. ban players"
    default: op
